### ISSUE TITLE
Changes are not being upstreamed to original cJSON

### ISSUE THREAD

**Issue by thiagomacieira** [kbranigan/cJSON#12]
This repository is effectively a fork (in the non-GitHub sense) of the original cJSON. None of your changes are being upstreamed to the original maintainer, who seems to still be active in maintaining cJSON. Please choose whether you're a permanent fork or not.

If you decide you're a permanent fork, please kindling rename the project and make it clear in your README that this is a fork from the original.

If you decide that you're going to cooperate with Dave, please upstream all the changes you have here. If you keep accepting further pull requests, which you're allowed to, you will need to work with the upstream maintainer to get the changes in. He may not want some or all of them, in which case you will have to reject the pull request.

**Comment by kbranigan** [comment]
Heyo, Thanks for the comment.  The primary difference between this repo and the original is the addition of build files.  

    Only in cJSON/: CMakeLists.txt
    Only in cJSON/: Makefile
    Only in cJSON/: README.md

There are two code changes:

    diff cJSON/cJSON.c cjson-code/cJSON.c
    620c620
    <     while (child && !fail)
    ---
    >     while (child)
    diff cJSON/test.c cjson-code/test.c
    49c49
    <   data=(char*)malloc(len+1);fread(data,1,len,f);data[len]='\0';fclose(f);
    ---
    >   data=(char*)malloc(len+1);fread(data,1,len,f);fclose(f);

I will create an account on sourceforge and see if davegamble wants them.  It seems like development has stopped though as he doesn't check tickets and no updates have been made in 6 months.  If no response is received then I will take no further actions.

**Comment by thiagomacieira** [comment]
You don't need an account, just mail him the patches with a good explanation why they exist.

**Comment by netsurf916** [comment]
According to the maintainer on Sourceforge, this repo is considered more "up-to-date" and he is planning to migrate to github -- presumably on this project.  I've had trouble getting fixes for crashes as a result.  I would actually consider cJSON to be unmaintained at this point.
