### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by anton-sergeev** [kbranigan/cJSON#21]
In [cJSON_Utils.c#L208](https://github.com/kbranigan/cJSON/blob/2fbe478d215fadbb21aadfe0ffc868fc338ae9df/cJSON_Utils.c#L208) logical inconsistencies:
```c
	if (!patches->type==cJSON_Array) return 1; /* malformed patches. */
```

I assume here should be:
```c
	if (patches->type!=cJSON_Array) return 1; /* malformed patches. */
```

**Comment by FSMaxB** [comment]
I made a pull request #19 and also sent a patch to the original cJSON.

**Comment by kbranigan** [comment]
geez, that's an embarrassing one
