### ISSUE TITLE
Did you ever consider using union in your cJSON data structure?

### ISSUE THREAD

**Issue by zichuanwang** [kbranigan/cJSON#3]
I think it will save some space...Ignore this issue if I'm being naive. Thanks.

**Comment by 2mac** [comment]
Depending on the number of instances of the cJSON structure, this actually could make a meaningful impact on memory usage. I agree.

However, this is not the original repository for this software. Consider submitting this issue to the author (http://cjson.sourceforge.net/), or create your own patch if you're up for it.
