### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by bungle** [kbranigan/cJSON#33]
This is discussed here:
https://github.com/bungle/lua-resty-libcjson/issues/6

That is LuaJIT FFI binding to this library. There is also an example that triggers this problem. I'm pretty sure the leak is in C-module, but it could be in my code as well, but I have not spotted it.

**Comment by someburner** [comment]
I'm not familiar with Lua or LuaJIT but any memory leaks I've ever encountered with this library have been issues in my code with not properly freeing the alloc'd memory (i.e. calling cJSON_Delete). Perhaps provide a snippet of what .encode looks like in your implementation?

**Comment by bungle** [comment]
The encode looks like this:
https://github.com/bungle/lua-resty-libcjson/blob/master/lib/resty/libcjson.lua#L128

**Comment by someburner** [comment]
So when does the garbage collection happen? Again, not familiar with the platform but if the loop is blocking and GC doesn't happen, one would expect the usage to increase until GC.

**Comment by bungle** [comment]
I think it leaks even with single call to that encode. And GC doesn't free it, that's why I suspect the problem is with C code, but not sure.

**Comment by bungle** [comment]
I have also tried manually calling `cJSON_Delete`s, but that leaks also.

**Comment by someburner** [comment]
Interesting. Have you tried printing out pointers of the objects created (if that's possible)? That way you can at least be sure it's trying to delete the right thing.

**Comment by bungle** [comment]
Yes, let's see here the problem is, possible places:

1. https://github.com/bungle/lua-resty-libcjson/issues/6
2. https://github.com/LuaJIT/LuaJIT/issues/163
3. https://github.com/kbranigan/cJSON/issues/33

I tried even more test on my bindings, and whatever I do, I see `luajit` taking more and more memory while it is running.

**Comment by bungle** [comment]
@someburner, Yes, the error was in 1. (aka my code) after all. Thanks for helping and looking at it.
