### ISSUE TITLE
My JSON doesn't get parsed correctly 

### ISSUE THREAD

**Issue by medha-joshi** [kbranigan/cJSON#43]
While parsing the below json, elements ipv4 and ipv6 are not parsed as CJSON_Array. They are parsed as cJSON_NULL and I am wondering why ? Does "ipv6" : null at one place (marked in bold) throws the parsing off ?

Thanks,

Medha

{
  "data": {
    "IDN": {
      "ipv4": [
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65031,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.3.1",
          "elapsed-time": {
            "tb1-vrr01": 3986,
            "tb1-vrr02": 4005
          },
          "vpn": "IDN"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65031,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Connect",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.3.2",
          "elapsed-time": {
            "tb1-vrr01": 3986,
            "tb1-vrr02": 4005
          },
          "vpn": "IDN"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65032,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Connect",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.3.3",
          "elapsed-time": {
            "tb1-vrr01": 3988,
            "tb1-vrr02": 4006
          },
          "vpn": "IDN"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65032,
          "instances": [
            "tb1-vrr02",
            "tb1-vrr01"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.3.4",
          "elapsed-time": {
            "tb1-vrr01": 3988,
            "tb1-vrr02": 4007
          },
          "vpn": "IDN"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65033,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Connect",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.3.5",
          "elapsed-time": {
            "tb1-vrr01": 3990,
            "tb1-vrr02": 4006
          },
          "vpn": "IDN"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65033,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Connect",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.3.6",
          "elapsed-time": {
            "tb1-vrr01": 3989,
            "tb1-vrr02": 4005
          },
          "vpn": "IDN"
        }
      ],
      **"ipv6": null**  
    },
    "VCP": {
      "ipv4": [
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.2.1",
          "elapsed-time": {
            "tb1-vrr01": 3988,
            "tb1-vrr02": 4004
          },
          "vpn": "VCP"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Connect",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.2.2",
          "elapsed-time": {
            "tb1-vrr01": 3984,
            "tb1-vrr02": 4007
          },
          "vpn": "VCP"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Active"
          },
          "peer-address": "169.254.2.17",
          "elapsed-time": {
            "tb1-vrr01": 3993,
            "tb1-vrr02": 4005
          },
          "vpn": "VCP"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Connect"
          },
          "peer-address": "169.254.2.18",
          "elapsed-time": {
            "tb1-vrr01": 3992,
            "tb1-vrr02": 4006
          },
          "vpn": "VCP"
        }
      ],
      "ipv6": [
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Active"
          },
          "peer-address": "fdf8::2:1",
          "elapsed-time": {
            "tb1-vrr01": 3994,
            "tb1-vrr02": 4005
          },
          "vpn": "VCP"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Connect",
            "tb1-vrr02": "Connect"
          },
          "peer-address": "fdf8::2:2",
          "elapsed-time": {
            "tb1-vrr01": 3984,
            "tb1-vrr02": 4006
          },
          "vpn": "VCP"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Active"
          },
          "peer-address": "fdf8::2:81",
          "elapsed-time": {
            "tb1-vrr01": 3986,
            "tb1-vrr02": 4007
          },
          "vpn": "VCP"
        },
        {
          "accepted-prefix-count": 0,
          "active-prefix-count": 0,
          "received-prefix-count": 0,
          "suppressed-prefix-count": 0,
          "peer-as": 65002,
          "instances": [
            "tb1-vrr01",
            "tb1-vrr02"
          ],
          "peer-state": {
            "tb1-vrr01": "Active",
            "tb1-vrr02": "Connect"
          },
          "peer-address": "fdf8::2:82",
          "elapsed-time": {
            "tb1-vrr01": 3994,
            "tb1-vrr02": 4006
          },
          "vpn": "VCP"
        }
      ]
    },
    "vpn-names": [
      "VCP",
      "IDN"
    ]
  },
  "data_source": "rest",
  "operation": "post_response",
  "resource": "bgp_peer_summary",
  "system_id": "bgp"
}

**Comment by kbranigan** [comment]
have you tried the most recent version of the code available at https://github.com/DaveGamble/cJSON ?  (Let me know and I'll pull his changes)

**Comment by medha-joshi** [comment]
I am not sure. Let me compare.

**Comment by medha-joshi** [comment]
I was running with library version 1.5.6.  I built version 1.7.3 that you sent. Thanks a lot for promptly sending it ! ! Btw, it's a cool and lightweight library.

**Comment by medha-joshi** [comment]
I forgot to mention, the problem is solved in the latest version.
