### ISSUE TITLE
cJSON  new version ? 

### ISSUE THREAD

**Issue by edsiper** [kbranigan/cJSON#5]
I got a notification from sourceforge site that a new version of cJSON is available. I got the tarball and there is a lot of C code differences. 

Anyone of you knows what are the changes about ? are those changes merged into this repository ?

note: if you know how to contact Dave Gamble please let me know

**Comment by kbranigan** [comment]
I'm not familiar with the changes, I downloaded cJSON at one point when it seemed like it wasn't being updated and uploaded it here - I'm willing to merge in changes if you've worked with the new code and it's all improvements

**Comment by TravisPaul** [comment]
I just downloaded the latest cJSON source from SourceForge and can report that there is only one difference between the cJSON.h and cJSON.c files in the two repos at line 620 of cJSON.c.  This repo has a check for ```!fail``` that the other does not (which appears to be an improvement.)

[Github/kbranigan](https://github.com/kbranigan/cJSON/blob/master/cJSON.c#L620)
```C
		while (child && !fail)
		{
			names[i]=str=print_string_ptr(child->string,0);
			entries[i++]=ret=print_value(child,depth,fmt,0);
			if (str && ret) len+=strlen(ret)+strlen(str)+2+(fmt?2+depth:0); else fail=1;
			child=child->next;
		}
```

[Source Forge/davegamble](http://sourceforge.net/p/cjson/code/HEAD/tree/cJSON.c#l620)
```C
		while (child)
		{
			names[i]=str=print_string_ptr(child->string,0);
			entries[i++]=ret=print_value(child,depth,fmt,0);
			if (str && ret) len+=strlen(ret)+strlen(str)+2+(fmt?2+depth:0); else fail=1;
			child=child->next;
		}
```

Just though I would share my findings with anyone who came across this.

**Comment by kbranigan** [comment]
There are a bunch of new changes now, mostly minor bug fixes.

**Comment by TravisPaul** [comment]
Thanks for the update, glad to see this fork of cJSON continuing to get improvements!
